version: 2.1

jobs:
  build-and-test:
    docker:
     - image: cimg/python:3.10

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # Check for a requirements.txt file and install dependencies if it exists
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi
      - run:
          name: Run tests
          command: python test.py

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test